karma-u:
	npm uninstall karma karma-chrome-launcher karma-coverage karma-jasmine karma-jasmine-html-reporter @types/jasmine jasmine-core

jest-i:
	npm i - save-dev jest @types/jest  jest-preset-angular @angular-builders/jest